# Generated by Django 5.2.6 on 2025-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_review_avg_watchlist_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='review_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
