# Generated by Django 5.2.6 on 2025-09-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_alter_watchlist_review_avg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='review_avg',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='review_count',
            new_name='number_rating',
        ),
    ]
